[package]
authors = ["Victor M. Suarez <svmnotn@gmail.com>"]
description = "A library for all your dice rolling needs."
license = "MIT"
name = "potential-system"
readme = "README.md"
repository = "https://github.com/svmnotn/potential-system"
version = "0.1.0"

[dependencies]
rand = "*"
