avg_planets = 8
min_planets = 2
max_planets = 12
[star_types."A Class Star"]
chance = 0.625
part_multy = 0.8
make_multy = 0.1
rocky = 0.4
gas = 0.5
belts = 0.35
description = 'A-type stars are among the more common naked eye stars, and are white or bluish-white. About 1 in 160 (0.625%) of the main-sequence stars in the solar neighborhood are A-type stars.'

[star_types."B Class Star"]
chance = 0.125
part_multy = 0.6
make_multy = 0.05
rocky = 0.35
gas = 0.4
belts = 0.25
description = 'B-type stars are very luminous and blue. About 1 in 800 (0.125%) of the main-sequence stars in the solar neighborhood are B-type main-sequence objects.'

[star_types."Black Hole"]
chance = 0.1
part_multy = 0.1
make_multy = 0.9
rocky = 0.1
gas = 0.09
belts = 0.2
description = 'A black hole is a region of spacetime exhibiting such strong gravitational effects that nothing—not even particles and electromagnetic radiation such as light—can escape from inside it. The theory of general relativity predicts that a sufficiently compact mass can deform spacetime to form a black hole.'

[star_types."D Class Star"]
chance = 0.75
part_multy = 0.3
make_multy = 0.6
rocky = 0.25
gas = 0.21
belts = 0.34
description = 'Class D (for Degenerate) is the modern classification used for white dwarfs – low-mass stars that are no longer undergoing nuclear fusion and have shrunk to planetary size, slowly cooling down.'

[star_types."F Class Star"]
chance = 3.03
part_multy = 0.7
make_multy = 0.08
rocky = 0.45
gas = 0.55
belts = 0.4
description = 'F-type stars are white in color. About 1 in 33 (3.03%) of the main-sequence stars in the solar neighborhood are F-type stars'

[star_types."G Class Star"]
chance = 7.5
part_multy = 0.4
make_multy = 0.05
rocky = 0.6
gas = 0.6
belts = 0.2
description = 'Class G main-sequence stars make up about 7.5%, nearly one in thirteen, of the main-sequence stars in the solar neighborhood.'

[star_types."K Class Star"]
chance = 12.0
part_multy = 0.5
make_multy = 0.02
rocky = 0.5
gas = 0.4
belts = 0.4
description = 'K-type stars are orangish stars that are slightly cooler than the Sun. They make up about 12%, nearly one in eight, of the main-sequence stars in the solar neighborhood.'

[star_types."M Class Star"]
chance = 76.0
part_multy = 0.56
make_multy = 0.01
rocky = 0.8
gas = 0.4
belts = 0.3
description = 'Class M stars are by far the most common. About 76% of the main-sequence stars in the solar neighborhood are class M stars. However, class M main-sequence stars (red dwarfs) have such low luminosities that none are bright enough to be seen with the unaided eye, unless under exceptional conditions.'

[star_types."Neutron Star"]
chance = 0.5
part_multy = 0.2
make_multy = 0.7
rocky = 0.2
gas = 0.1
belts = 0.3
description = 'A neutron star is the collapsed core of a large star which before collapse would have had a total of between 10 and 29 solar masses. Neutron stars are the smallest and densest stars known to exist. Though neutron stars typically have a radius on the order of 10 kilometres (6.2 mi), they can have masses of about twice that of the Sun. They result from the supernova explosion of a massive star, combined with gravitational collapse, that compresses the core past the white dwarf star density to that of atomic nuclei.'

[star_types."O Class Star"]
chance = 0.00003
part_multy = 0.05
make_multy = 0.06
rocky = 0.3
gas = 0.4
belts = 0.2
description = 'O-type stars are very hot and extremely luminous, with most of their radiated output in the ultraviolet range. These are the rarest of all main-sequence stars. About 1 in 3,000,000 (0.00003%) of the main-sequence stars in the solar neighborhood are O-type stars.'

[rocky]
moon = 0.4
belt = 0.2

[gas]
belt = 0.7
avg_moon = 4
min_moon = 1
max_moon = 12
